on: "push"

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - run: ls -la
    - uses: actions/checkout@v1
    - run: ls -la

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: change folders
      run: cd src
      
    - name: npm install, make app
      run: |
        npm install
        make app

    - name: Coveralls
      uses: coverallsapp/github-action@v2